---
# User configuration
username: antoine.vankampen@mydre.org

libasound: libasound2 # If libasound2 doesn't work, try libasound2t64

# Rclone configuration
remote_path: "RD:"
local_mount: "/home/antoine.vankampen@mydre.org/Desktop/RD"
root_path: "/home/antoine.vankampen@mydre.org"

# Feature flags  (only add this if we want to configure it here, instead of command line)
run_General: true
run_Vscode: true
run_Conda: true
run_Emacs: true
run_run_Julia: true
run_run_Containers: true
run_Compilers: true
run_R: true
run_Bashrc: true
